version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: boilerplate-node:latest
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/boilerplate
      JWT_SECRET: super-secret-change-me
      JWT_ISSUER: boilerplate-node
      JWT_TTL: 900s
      COOKIE_SECRET: change-me-cookie
      GOOGLE_CLIENT_ID: your-google-client-id
      GOOGLE_CLIENT_SECRET: your-google-client-secret
      GOOGLE_CALLBACK_URL: http://localhost:3000/api/v1/auth/google/callback
      SENTRY_DSN: ''
      CORS_WHITELIST: http://localhost:3000
      LOG_DIR: /var/log/app
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - logs:/var/log/app
    command: npm run dev

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.9
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres-data:
  logs:
